# Generated by Django 3.2.12 on 2022-02-12 05:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=400)),
                ('location', models.CharField(max_length=200)),
                ('min_salary', models.IntegerField(blank=True, null=True)),
                ('max_salary', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_expired', models.DateTimeField(blank=True, null=True)),
                ('job_description', models.TextField()),
                ('job_url', models.URLField()),
            ],
        ),
    ]
