# Generated by Django 3.2.12 on 2022-03-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinnedjobs',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='user_notes', to='job_search.Notes'),
        ),
    ]
