# Generated by Django 3.2.12 on 2022-02-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsearch',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
