# Generated by Django 3.2.12 on 2022-03-19 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='short_description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pinnedjobs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
