# Generated by Django 3.2.12 on 2022-04-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0002_pinnedjobs_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
