# Generated by Django 3.2.12 on 2022-02-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0003_auto_20220214_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='PinnedJob'),
        ),
    ]
