# Generated by Django 3.2.12 on 2022-03-19 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0003_auto_20220319_0239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='notes',
            name='related_job',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='related_job', to='job_search.job'),
        ),
    ]
