# Generated by Django 3.2.12 on 2022-04-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0003_job_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(0, 'hidden'), (1, 'Public')], default=1),
        ),
    ]
