# Generated by Django 3.2.12 on 2022-02-15 11:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0004_auto_20220214_0205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(default=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='short_description',
            field=models.CharField(blank=True, default=False, max_length=200, null=True),
        ),
    ]
