# Generated by Django 3.2.12 on 2022-04-12 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0004_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='related_job',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, related_name='related_job', to='job_search.job'),
        ),
    ]
