# Generated by Django 3.2.12 on 2022-02-15 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0005_auto_20220215_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(default=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True), editable=False, max_length=200, unique=True),
        ),
    ]
