# Generated by Django 3.2.12 on 2022-04-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0007_alter_notes_related_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
