# Generated by Django 3.2.12 on 2022-02-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0007_auto_20220221_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(0, 'hidden'), (1, 'Public')], default=0),
        ),
    ]
