# Generated by Django 3.2.12 on 2022-03-07 02:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_search', '0009_auto_20220307_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinnedjob',
            name='is_pinned',
            field=models.ManyToManyField(blank=True, related_name='is_pinned', to=settings.AUTH_USER_MODEL),
        ),
    ]
